We simulate a set of sequences as a numeric matrix:

In [6]:
!git clone https://github.com/uio-bmi/bionumpy-example-data

Cloning into 'bionumpy-example-data'...
remote: Enumerating objects: 4, done.
remote: Counting objects: 100% (4/4), done.
remote: Compressing objects: 100% (3/3), done.
remote: Total 4 (delta 0), reused 4 (delta 0), pack-reused 0
Unpacking objects: 100% (4/4), 235.19 KiB | 519.00 KiB/s, done.


In [5]:
import numpy as np
sequence_length = 10
n_sequences = 5
sequences = np.random.randint(0, 4, (n_sequences, sequence_length))
print(sequences)

[[1 3 1 3 0 0 0 1 0 0]
 [2 0 2 1 0 0 2 0 3 2]
 [3 1 3 0 3 0 1 1 0 1]
 [3 1 3 3 0 3 1 3 0 1]
 [0 1 3 0 2 3 0 3 2 1]]
