We simulate a set of sequences as a numeric matrix:

In [5]:
import numpy as np
sequence_length = 10
n_sequences = 5
sequences = np.random.randint(0, 4, (n_sequences, sequence_length))
print(sequences)

[[1 3 1 3 0 0 0 1 0 0]
 [2 0 2 1 0 0 2 0 3 2]
 [3 1 3 0 3 0 1 1 0 1]
 [3 1 3 3 0 3 1 3 0 1]
 [0 1 3 0 2 3 0 3 2 1]]
